# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

try:
  from . import scanner_pb2 as scanner__pb2
except ImportError:
  import scanner_pb2 as scanner__pb2


class ScannerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Scan = channel.unary_unary(
                '/scan.Scanner/Scan',
                request_serializer=scanner__pb2.ScanRequest.SerializeToString,
                response_deserializer=scanner__pb2.ScanResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/scan.Scanner/Read',
                request_serializer=scanner__pb2.ReadRequest.SerializeToString,
                response_deserializer=scanner__pb2.ScanResponse.FromString,
                )


class ScannerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Scan(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=scanner__pb2.ScanRequest.FromString,
                    response_serializer=scanner__pb2.ScanResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=scanner__pb2.ReadRequest.FromString,
                    response_serializer=scanner__pb2.ScanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scan.Scanner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scanner(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scan.Scanner/Scan',
            scanner__pb2.ScanRequest.SerializeToString,
            scanner__pb2.ScanResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scan.Scanner/Read',
            scanner__pb2.ReadRequest.SerializeToString,
            scanner__pb2.ScanResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
